### ISSUE TITLE
Stuck at ImportError: cannot import name save_numpy_as_midi

### ISSUE THREAD

**Issue by ghost** [jmmcd/drum-manifold#1]
I'm stuck at these two spots, just wondering if we can get a tutorial on how to work it?

`  File "vae.py", line 30, in <module>
    from midi2numpy import save_numpy_as_midi
ImportError: cannot import name save_numpy_as_midi`

`python midi2numpy.py
Traceback (most recent call last):
  File "midi2numpy.py", line 332, in <module>
    cmd = sys.argv[1]
IndexError: list index out of range`

**Comment by jmmcd** [comment]
Sorry about that! Please pull and re-try. Added some notes in the README.md (front page of Github repo).
